### ISSUE TITLE
New Coder trying to Debug in console

### ISSUE THREAD

**Issue by Nick-Achee** [jherr/chat-o-matic#4]
Hi Jack

I am about 11 minutes into the video and have had success until I try setting up <Chat /> in the App.jsx.
Usually I would give up and move to another tutorial by now but I am going to try and finish.

when I remove the original <div> in App.jsx and try to use <Chat / > nothing comes up. Server is still running fine. Im not sure how to debug but I tried to look into it and could not find an explanation but I did get this message in the console and I will post a screenshot now. Not sure what else to try?
![Screen Shot 2020-08-30 at 11 38 21 PM](https://user-images.githubusercontent.com/64217718/91689926-e9f3cc00-eb19-11ea-955e-ea0e8019a5f9.png)

Also thank you for the videos!

**Comment by jherr** [comment]
Is the GraphQL server still running? Failing for fetch probably means that either the URL is wrong, or the server isn't responding.

**Comment by Nick-Achee** [comment]
Ok so after messing with it back and forth all day I finally realized I had an incorrect element in my chat component. Seriously thank you for the response and sharing all of your wisdom. You are a legend! Back to the video!

**Comment by jherr** [comment]
Haha, it's always something.

**Comment by Nick-Achee** [comment]
Hi Jack! 

Again thank you for creating this tutorial 🤙

Im curious what your recommendation for  deploying  this app would be?

Thinking this would be cool to deploy then turn the url into a QR code and leave that around town and see if people would interact with it. The idea being having a different prompt in the <h1> every day or so.. and maybe some drone footage in the background of the town.. might boost local morale.  

I would greatly appreciate any feedback about deployment/hosting! 

Thanks,
Nick

**Comment by jherr** [comment]
Probably Heroku. You need something that's going to run the server so that you have the GraphQL API doing to work of managing the messages.

**Comment by jherr** [comment]
Gonna close this out. Looks to be resolved.
